version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/test_app
    ports:
      - 8000:8000
    image: app:test_app
    container_name: test_app
    command: python manage.py runserver 0.0.0.0:8000