# Generated by Django 4.1.9 on 2023-06-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("92ca42ac-6203-4642-8192-42d3175df6cf"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("about_me", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image_path",
                    models.CharField(
                        default="media/profile_images/blank_profile.png",
                        max_length=100000,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
