# Generated by Django 4.1.9 on 2023-06-21 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("82ab7bfe-27d6-4060-afc1-106cf2b9b9d7"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
