# Generated by Django 4.1.9 on 2023-06-22 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("870240f3-5f9f-440f-ab3e-d08d6225c4a7"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_path",
            field=models.CharField(
                default="https://firebasestorage.googleapis.com/v0/b/socialmediatiny.appspot.com/o/media%2Fprofile_images%2Fblank_profile.png?alt=media&token=a7798e1c-3621-486e-b025-1befb1c0caf8",
                max_length=100000,
            ),
        ),
    ]
