# Generated by Django 4.1.9 on 2023-06-22 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_id_alter_profile_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7542799a-d95c-4641-acef-e3cccd4a320d"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
