# Generated by Django 4.1.9 on 2023-06-23 07:00

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_alter_profile_id_post_like_imagesofpost_comment"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comment", new_name="CommentOfPost",),
        migrations.RenameModel(old_name="Like", new_name="LikeOfPost",),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3a506ff-0a97-45b7-be9c-bfb1539e38ff"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
