# Generated by Django 4.1.9 on 2023-06-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_commentofpost_id_alter_imagesofpost_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagesofpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.post",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
