# Generated by Django 4.1.9 on 2023-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_commentofpost_post_alter_likeofpost_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentofpost",
            name="comment",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
