# Generated by Django 4.1.9 on 2023-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="location",),
        migrations.AddField(
            model_name="post",
            name="no_of_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image_path",
            field=models.ImageField(
                default="blank_profile.png", upload_to="profile_images"
            ),
        ),
    ]
