# Generated by Django 4.1.9 on 2023-07-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_likeofpost_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_enabled_comments",
            field=models.BooleanField(default=True),
        ),
    ]
