# Generated by Django 4.2.3 on 2023-07-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=100000),
        ),
    ]
